version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: inventory_api
    volumes:
      - .:/inventory_api
    ports:
      - "8000:8000"
    env_file:
      - ./inventory_api/.env
    depends_on:
      - db
    stdin_open:   true
    tty:  true
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=inventory
      - POSTGRES_PASSWORD=inventory
      - POSTGRES_DB=inventoryapp_db
volumes:
  postgres_data: